### ISSUE TITLE
Partilhar com o facebook

### ISSUE THREAD

**Issue by ricardoJmarques** [cesium/sei16#2]
erro em  "http://intra.seium.org".
Na home quando o utilizador faz share com facebook aparece como titulo a SEI15 e não a 16. Printscreen em anexo. User:lead

![captura de ecra de 2016-02-13 00 20 58](https://cloud.githubusercontent.com/assets/17221661/13029088/276f8e88-d27a-11e5-813d-a8689a42b729.png)

**Comment by miguelpinto98** [comment]
Esta issue não é referente a este projeto.
Look hear: https://github.com/cesium/intra.seium.org
